language: node_js
node_js:
  - 'iojs'
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - apt-get install libgnome-keyring-dev
  - git clone git@github.com:atom/apm.git --depth=10
  - cd apm
  - npm install
  - grunt
install:
  - apm/bin/apm install
script:
  - npm test
