language: node_js
node_js:
  - 'iojs'
sudo: required
cache:
  directories:
    - node_modules
before_install:
  - git clone git@github.com:atom/apm.git --depth=10
  - cd apm
  - npm install
  - grunt
install:
  - apm/bin/apm install
script:
  - npm test
addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
